# https://docs.docker.com/compose/compose-file/
name: pantheon

services:
    db:
        container_name: pantheon-db
        image: postgres

        ports:
            - ${DB_PORT}

        volumes:
            - data:/data/db

        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}

    app:
        container_name: pantheon-api
        build: .
        env_file: .env
        ports:
            - ${API_PORT}
        restart: ${RESTART_POLICY}
        mem_limit: ${HARD_MEMORY_LIMIT}
        mem_reservation: ${SOFT_MEMORY_LIMIT}
        depends_on:
            - db
        environment:
            # localhost (or whatever PostgresSQL's address actually is) cannot
            # be addressed directly from inside a container, instead we address
            # its container.
            - DB_HOST=pantheon-db
volumes:
    data: {}
